apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/thoth-devops
- ../../../../components/project-admin-rolebindings/pulp
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/medium
kind: Kustomization
namespace: thoth-pulp-experiments
resources:
- namespace.yaml
