---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thoth-test-core

resources:
- namespace.yaml
- resourcequota.yaml

components:
- ../../../components/project-admin-rolebindings/thoth
- ../../../components/limitranges/default
