apiVersion: v1
kind: ResourceQuota
metadata:
  name: thoth-middletier-prod-custom
spec:
  hard:
    count/pods: '625'
    count/workflows.argoproj.io: 1.5k
    limits.cpu: '16'
    limits.memory: 48Gi
    requests.cpu: '16'
    requests.memory: 32Gi
    requests.storage: 64Gi
    count/objectbucketclaims.objectbucket.io: 1
