apiVersion: user.openshift.io/v1
kind: Group
metadata:
    name: thoth
    annotations:
        kustomize.config.k8s.io/behavior: replace
users:
- ENC[AES256_GCM,data:UudExMPhizTj7GJAlLiFQEk=,iv:l5DKt6mFOKzqVMqS5CWquMFS+yXPIsrar6IhxsUUcek=,tag:SxojJRdc2bRpbX6xmi+R1g==,type:str]
- ENC[AES256_GCM,data:y+UvB7FDY3L0OR0BmGTeFHyZrw==,iv:syl/vrTf3+YsHPJv+HR5VnWxJLl7pemMgLGv880u3Bc=,tag:0epOmdQC4q9JiLb5cvFBlw==,type:str]
- ENC[AES256_GCM,data:KMXV1OWh0e6rgR8oOV3nYSQ/Mg==,iv:GymdcoPCjeDt57+ljSjyLHq2eBxjsDqhzn4ywL3Esgg=,tag:kBMLJGBOXwRewCXQE7ijOg==,type:str]
- ENC[AES256_GCM,data:kOn0043wv7t0T6H4Q4fctLM=,iv:sNAhmck3gQRWT+rp/9hzNTZ3FPaPV3OVczMAfiFKl+U=,tag:JxUvt0KAv2dd0NbtDEQPXA==,type:str]
- ENC[AES256_GCM,data:0MAyr2KLl4sF110aaAhxaVfVeg==,iv:LyRzvHShChKUzXOAZNYWgxs7Xu9RHIB7NHEHw0Mkk58=,tag:QGMEB8U7HLHVGqIOgdkVDQ==,type:str]
- ENC[AES256_GCM,data:rxfbzymWx/aO56Tt0Kh2QJt/mA==,iv:lLbLUgI8Yh73RPQGmTvxKW4fuSFDIdwjdxrM+pgiD4I=,tag:qUNc6q2QnNhUkbd7sDQRTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-04-07T15:06:53Z'
    mac: ENC[AES256_GCM,data:O97Ldm1JFfiKkhv+vwZ5E9wJxpk4elbcOwe1FY1i1QJgrvk4hFgy7eD2WVixi5rkG8DAn3B7NG3NpMWfA/1ZdGAMNhJuOqv9F/55oFmu0yhFQR49ESd2tgYDOMcLqirorhK96hk27Xxe/t0b9zuQGJV9GXGiJYlH4zeD/OaP4g0=,iv:Fl4TWARrGu0inhrl418KnRrWvL98LqsT7lAEWJB4bbc=,tag:DxnP5yJrZqjOJJxnrmhRWg==,type:str]
    pgp:
    -   created_at: '2021-04-07T15:06:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ//WgTiWGPBSFkxyy776h9v1T3lEvWY87PGDPEsP1DzkvpP
            93VsF3s6/F5WdPm0OTyiPAmXjP67ce1aMDcVfR7aeYmJmh6qFN3O4chp6ZvGSSGc
            MZDIWp1UaglZ689teQcJ83ALZUtCaRiFgwW8TKoCMuzCXu2kLf+Tv6z1yVOyEMJx
            jmf7aR0a0KI0jTazARnRU5nYAkAmqMz/B6+6FPGsdAP4oBpFgBX7++ECmul2Oj1i
            ggcoE+YsSJatRAaKrAi0TopcI/6VPvWoLSzw1zYVQ9kW+epbhjW6HKTclFBBYaI9
            kzx+x+CVVBEpz2gQWoUJx9q71LTNB4St3eKXem2FxmgAabigexF9M7Mg2HaP0542
            qk8rc81gYpwtxwO6qmLewDFdN/GrwYVlUdPloBbpRm97pM6j82ioQhnaZjsY/V37
            4BpYRnHqd5kDfAGcapHYfMwO6KLYaNPZFfdWAj/uCTAaDO2ENGditabnqU7TEaTh
            b5vtNe3aFXCoaVtOsL6VrP9CnzAjzS6EJ9jwNup7CaIpGfT4qRKnoAIEBPEj+6hQ
            q17I+StPjdKG3ebFL2xaNLQQB2zoAnW9Q+481rQxlYaAtawRut/ZDfaoFuOXgjMp
            HTLjubWq4UUyaP7YlgZl8MMwqpbEKSHbsGJLfQr8y2+oR9X8vuu4m2A1g/T/gRLS
            XgFJndZXs+d/zgNZ9bYLnUfcptcAjxSxXc9qWukHH6xdKEpynLBu3+WNmAVxHSM8
            1EGkPq3253tI+Kt5pUH4KurqQDggEa6q5PU5uXEkJU+3bOufi51ic9YEGszm4Ug=
            =On28
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(users|data|stringData)$
    version: 3.5.0
